# Generated by Django 4.2.7 on 2026-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_is_flash_sale_product_is_free_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_end',
            field=models.DateTimeField(blank=True, help_text='Flash sale ending time', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted flash sale price', max_digits=10, null=True),
        ),
    ]
