# Generated by Django 4.2.7 on 2026-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_flash_end_product_flash_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'display_order']},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=9999, help_text='Lower number shows first.', verbose_name='Display Order'),
        ),
    ]
