# Generated by Django 4.2.7 on 2026-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_abandonedcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='last_promotion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='promotion_sent',
            field=models.BooleanField(default=False),
        ),
    ]
