# Generated by Django 4.2.7 on 2026-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_productimage_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'stock'], name='store_produ_availab_56ed7b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'featured'], name='store_produ_availab_194bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'is_flash_sale'], name='store_produ_availab_d6a5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['views'], name='store_produ_views_4899cb_idx'),
        ),
    ]
