# Generated by Django 4.2.7 on 2026-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('flash_sale', 'Flash Sale'), ('free_delivery', 'Free Delivery'), ('new_arrival', 'New Arrival'), ('trending', 'Trending'), ('guest_checkout', 'Guest Checkout'), ('wishlist', 'Wishlist'), ('reviews', 'Reviews'), ('coupon', 'Coupon'), ('cod', 'Cash On Delivery'), ('emi', 'EMI'), ('maintenance', 'Maintenance Mode'), ('coming_soon', 'Coming Soon'), ('announcement', 'Announcement Bar')], max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
