# Generated by Django 4.2.7 on 2026-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_sale', models.BooleanField(default=True)),
                ('free_delivery', models.BooleanField(default=True)),
                ('trending', models.BooleanField(default=True)),
                ('new_arrival', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
