# Generated by Django 4.2.7 on 2026-07-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_websitefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('background_color', models.CharField(default='#ff3d3d', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement Bar',
                'verbose_name_plural': 'Announcement Bar',
            },
        ),
        migrations.DeleteModel(
            name='WebsiteFeature',
        ),
        migrations.RemoveField(
            model_name='featuretoggle',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='featuretoggle',
            name='key',
            field=models.CharField(choices=[('flash_sale', 'Flash Sale'), ('free_delivery', 'Free Delivery'), ('new_arrival', 'New Arrival'), ('trending', 'Trending'), ('guest_checkout', 'Guest Checkout'), ('wishlist', 'Wishlist'), ('reviews', 'Reviews'), ('coupon', 'Coupon'), ('cod', 'Cash On Delivery'), ('emi', 'EMI'), ('maintenance', 'Maintenance'), ('coming_soon', 'Coming Soon'), ('announcement', 'Announcement Bar')], max_length=50, unique=True),
        ),
    ]
