# Generated by Django 4.2.7 on 2026-07-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_announcementbar_delete_websitefeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
