# Generated by Django 4.2.7 on 2026-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_announcement_delete_announcementbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Shopora', max_length=100)),
                ('shop_tagline', models.CharField(blank=True, max_length=255)),
                ('announcement', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='website/')),
            ],
        ),
    ]
