# Generated by Django 4.2.7 on 2026-07-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_websitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'Website Settings', 'verbose_name_plural': 'Website Settings'},
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='copyright',
            field=models.CharField(blank=True, default='© 2026', max_length=255),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='Premium Electronics Store', max_length=255),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
