# Generated by Django 4.2.7 on 2026-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_websitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
