# Generated by Django 4.2.7 on 2026-07-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_websitesettings_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='announcement',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='facebook',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='instagram',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='shop_tagline',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='twitter',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='youtube',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
