# Generated by Django 4.2.7 on 2026-07-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_websitesettings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='copyright',
            field=models.CharField(blank=True, default='© 2026', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='favicon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='website/'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='Premium Electronics Store', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='website/'),
        ),
    ]
