# Generated by Django 4.2.7 on 2026-07-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_alter_websitesettings_copyright_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuretoggle',
            options={'ordering': ['category', 'key'], 'verbose_name': 'Feature Toggle', 'verbose_name_plural': 'Feature Toggles'},
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('customer', 'Customer'), ('payment', 'Payment'), ('website', 'Website')], default='website', max_length=30),
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='icon',
            field=models.CharField(default='⚙️', max_length=20),
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='featuretoggle',
            name='key',
            field=models.CharField(choices=[('flash_sale', 'Flash Sale'), ('free_delivery', 'Free Delivery'), ('new_arrival', 'New Arrival'), ('trending', 'Trending'), ('guest_checkout', 'Guest Checkout'), ('wishlist', 'Wishlist'), ('reviews', 'Reviews'), ('coupon', 'Coupon'), ('cod', 'Cash On Delivery'), ('emi', 'EMI'), ('announcement', 'Announcement Bar'), ('maintenance', 'Maintenance Mode'), ('coming_soon', 'Coming Soon')], max_length=50, unique=True),
        ),
    ]
