# Generated by Django 4.2.7 on 2026-07-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_featuretoggle_options_featuretoggle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('customer', 'Customer'), ('payment', 'Payment'), ('website', 'Website')], default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='featuretoggle',
            name='icon',
            field=models.CharField(default='⚙️', max_length=50),
        ),
    ]
