# Generated by Django 4.2.23 on 2026-07-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailotp',
            old_name='is_used',
            new_name='is_verified',
        ),
    ]
