# Generated by Django 4.2.23 on 2026-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_used_emailotp_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Verify Email'), ('reset', 'Reset Password'), ('login', 'OTP Login')], default='verify', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
