# Generated by Django 4.2.23 on 2026-07-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailotp_purpose_emailotp_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Verify Email'), ('reset', 'Reset Password'), ('login', 'OTP Login')], default='verify', max_length=20),
        ),
    ]
