# Generated by Django 4.2.7 on 2026-07-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_browser_user_device_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
