# Generated by Django 4.2.23 on 2026-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_coupo_order_coupon_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='one_time_per_user',
            field=models.BooleanField(default=False),
        ),
    ]
