# Generated by Django 4.2.23 on 2026-07-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_coupon_one_time_per_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=set(),
        ),
    ]
