# Generated by Django 4.2.7 on 2026-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_admin_note_order_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertimeline',
            name='created_by',
            field=models.CharField(default='System', max_length=100),
        ),
    ]
