# Generated by Django 4.2.7 on 2026-07-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_ordertimeline_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('sslcommerz', 'SSSCommerz'), ('stripe', 'Stripe'), ('emi', 'EMI')], default='cod', max_length=200),
        ),
    ]
