# Generated by Django 4.2.7 on 2026-07-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emi_months',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, '3 Months'), (6, '6 Months'), (9, '9 Months'), (12, '12 Months')], null=True),
        ),
    ]
