# Generated by Django 4.2.7 on 2026-07-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_emi_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('dhaka', 'Dhaka'), ('outside', 'Outside Dhaka')], max_length=20, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, default=0, help_text='USD Amount', max_digits=10)),
            ],
            options={
                'verbose_name': 'Delivery Charge',
                'verbose_name_plural': 'Delivery Charges',
                'ordering': ['city'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('dhaka', 'Dhaka'), ('outside', 'Outside Dhaka')], default='dhaka', max_length=20),
        ),
    ]
