# Generated by Django 4.2.7 on 2026-07-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_deliverycharge_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, choices=[('', 'Select Courier'), ('Steadfast', 'Steadfast'), ('RedX', 'RedX'), ('Pathao', 'Pathao'), ('Sundarban', 'Sundarban Courier'), ('Paperfly', 'Paperfly'), ('SA Paribahan', 'SA Paribahan'), ('Others', 'Others')], max_length=100),
        ),
    ]
