# Generated by Django 4.2.7 on 2026-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_refund_options_rename_note_refund_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='gateway_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('bank', 'Bank Transfer'), ('sslcommerz', 'SSLCommerz'), ('stripe', 'Stripe')], default='manual', max_length=30),
        ),
    ]
