# Generated by Django 4.2.7 on 2026-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_refund_gateway_response_refund_refund_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='courier_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exchange',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
